sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: X2QoYk0or5AJ2i4kfOqF2VvaF8uOrMBtsopFX9k0kEqmZSFvi1AkUUVCGhyCYt8MPdjb3INT2TKPW/df4tj61LrBt3e6BRbNFMLj0imEj7s5j3oetGRT4rdBv2Ar6JGWzCPcuKPsp2dMcpAxGVkfP/aH3J25v2ehoyTpK7gHmUI4TSA4F/i20u/9mxgyLjQXAuaaFpjKNX9z1hian32ezc7n5r+iwHQy7NXrBEnk0TeNMLWiYcZmvFM3Svr7IrtXy/UQcA/kfwFDzgiz3p2yQ1FTy6GlP+RFG88yRF7Bs954wrjemfPtjIAWtLVuQtiVzjVVaZQhJOfp46OsxBOgoyR5UOQxIHxcLNFEpD9tUrMz0AjzT8IMoNvlwImkKNBbdgX9vR6nf/dGhsGy/nXrOrEH40L9aS+ytwwjbEVPy1DqpQjPiFIZXSBz6dRBGqAaSRYaffTtkjaSQIzbKewBcMduTkHs9LTiPbWF9BVsvxi4lDjrAaIFFo0Sd5gkENf89aiV/2immEuB+Lbyrut8DEPQoo2aCKHjAYMYw567+QJC2J01CDL+LgHVdXnB/FgPBvJ2upHklV8YLpFdgx5rGqFirZsFDq4NYERi51No2BU0qQ3IDfu6ndSExlNFRpY1CPffgJAbf0mh+Z7wo+JdzDCaEQvCaWnGh6gest3AsZo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Society-s-Child-lyrics_3001
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy